In [2]:
import pandas as pd
import numpy as np

# NaN analysis in numpy array

In [9]:
# define a numpy array
array = np.array([[1, np.nan, 3], [4, 5, np.nan]])
array

array([[ 1., nan,  3.],
       [ 4.,  5., nan]])

In [10]:
# isna just provide the isna result on each element a provide a similar array with True and False
pd.isna(array)

array([[False,  True, False],
       [False, False,  True]])

In [11]:
# isnull is just a alias of isna
pd.isna(array)

array([[False,  True, False],
       [False, False,  True]])

In [19]:
# using ~ just reverse the True -> False
~pd.isna(array)

array([[ True, False,  True],
       [ True,  True, False]])

In [34]:
# show elements of them as  1d array
array[~pd.isna(array)]

array([1., 3., 4., 5.])

In [35]:
# show elements of them as  1d array
array[pd.isna(array)]

array([nan, nan])

In [74]:
array[np.array([[True,True,False],[False,True, True]])]

array([ 1., nan,  5., nan])

# NaN analysis in pandas dataframe

In [62]:
df = pd.DataFrame([['ant', 'bee', 'cat'], ['dog', None, 'fly'], [np.nan, 'snake', 'squirl'],], columns=['a','b','c'])
df

a      b       c
0  ant    bee     cat
1  dog   None     fly
2  NaN  snake  squirl

In [71]:
# fraction of events with NaN
print('fraction of events with NaN',df.isna().sum()/df.shape[0])

# fraction of events with NaN for a particular column
print('fraction of events with NaN for a particular column',df['a'].isna().sum()/df.shape[0])

fraction of events with NaN a    0.333333
b    0.333333
c    0.000000
dtype: float64
fraction of events with NaN for a particular column 0.3333333333333333


In [107]:
df[df.isnull()]

a     b    c
0  NaN   NaN  NaN
1  NaN  None  NaN
2  NaN   NaN  NaN

In [72]:
df[~df.isnull()]

a      b       c
0  ant    bee     cat
1  dog    NaN     fly
2  NaN  snake  squirl

## Selecting columns with/without nan

In [91]:
# for a particular columns, is there any NaN
pd.isna(df['a'])

0    False
1    False
2     True
Name: a, dtype: bool

In [92]:
# same as before
df['a'].isna()

0    False
1    False
2     True
Name: a, dtype: bool

In [101]:
# showing rows  having NaN in 'a' column
df[df['a'].isna()]

a      b       c
2  NaN  snake  squirl

In [100]:
# showing rows not having NaN in 'a' column
df[~df['a'].isna()]

a     b    c
0  ant   bee  cat
1  dog  None  fly

## Filling missing value

In [105]:
# filling for a particular columns
df_0 = df.copy()
df_0['a'] = df_0['a'].fillna(0)
df_0

a      b       c
0  ant    bee     cat
1  dog   None     fly
2    0  snake  squirl

In [106]:
# filling for entire df
df_0 = df.copy()
df_0 = df_0.fillna(0)
df_0

a      b       c
0  ant    bee     cat
1  dog      0     fly
2    0  snake  squirl